/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataDashboardRouteImport } from './routes/data-dashboard'
import { Route as HeatTransferRouteImport } from './routes/heat-transfer'
import { Route as PipeFlowRouteImport } from './routes/pipe-flow'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDashboardRoute = DataDashboardRouteImport.update({
  id: '/data-dashboard',
  path: '/data-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatTransferRoute = HeatTransferRouteImport.update({
  id: '/heat-transfer',
  path: '/heat-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const PipeFlowRoute = PipeFlowRouteImport.update({
  id: '/pipe-flow',
  path: '/pipe-flow',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-dashboard': typeof DataDashboardRoute
  '/heat-transfer': typeof HeatTransferRoute
  '/pipe-flow': typeof PipeFlowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-dashboard': typeof DataDashboardRoute
  '/heat-transfer': typeof HeatTransferRoute
  '/pipe-flow': typeof PipeFlowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-dashboard': typeof DataDashboardRoute
  '/heat-transfer': typeof HeatTransferRoute
  '/pipe-flow': typeof PipeFlowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/data-dashboard' | '/heat-transfer' | '/pipe-flow'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/data-dashboard' | '/heat-transfer' | '/pipe-flow'
  id: '__root__' | '/' | '/data-dashboard' | '/heat-transfer' | '/pipe-flow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataDashboardRoute: typeof DataDashboardRoute
  HeatTransferRoute: typeof HeatTransferRoute
  PipeFlowRoute: typeof PipeFlowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-dashboard': {
      id: '/data-dashboard'
      path: '/data-dashboard'
      fullPath: '/data-dashboard'
      preLoaderRoute: typeof DataDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heat-transfer': {
      id: '/heat-transfer'
      path: '/heat-transfer'
      fullPath: '/heat-transfer'
      preLoaderRoute: typeof HeatTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipe-flow': {
      id: '/pipe-flow'
      path: '/pipe-flow'
      fullPath: '/pipe-flow'
      preLoaderRoute: typeof PipeFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataDashboardRoute: DataDashboardRoute,
  HeatTransferRoute: HeatTransferRoute,
  PipeFlowRoute: PipeFlowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
