/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataDashboardRouteImport } from './routes/data-dashboard'
import { Route as HeatTransferRouteImport } from './routes/heat-transfer'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as PipeFlowRouteImport } from './routes/pipe-flow'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UnitsRouteImport } from './routes/units'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDashboardRoute = DataDashboardRouteImport.update({
  id: '/data-dashboard',
  path: '/data-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatTransferRoute = HeatTransferRouteImport.update({
  id: '/heat-transfer',
  path: '/heat-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const PipeFlowRoute = PipeFlowRouteImport.update({
  id: '/pipe-flow',
  path: '/pipe-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-dashboard': typeof DataDashboardRoute
  '/heat-transfer': typeof HeatTransferRoute
  '/manual': typeof ManualRoute
  '/pipe-flow': typeof PipeFlowRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/units': typeof UnitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-dashboard': typeof DataDashboardRoute
  '/heat-transfer': typeof HeatTransferRoute
  '/manual': typeof ManualRoute
  '/pipe-flow': typeof PipeFlowRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/units': typeof UnitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-dashboard': typeof DataDashboardRoute
  '/heat-transfer': typeof HeatTransferRoute
  '/manual': typeof ManualRoute
  '/pipe-flow': typeof PipeFlowRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/units': typeof UnitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-dashboard'
    | '/heat-transfer'
    | '/manual'
    | '/pipe-flow'
    | '/privacy'
    | '/terms'
    | '/units'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-dashboard'
    | '/heat-transfer'
    | '/manual'
    | '/pipe-flow'
    | '/privacy'
    | '/terms'
    | '/units'
  id:
    | '__root__'
    | '/'
    | '/data-dashboard'
    | '/heat-transfer'
    | '/manual'
    | '/pipe-flow'
    | '/privacy'
    | '/terms'
    | '/units'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataDashboardRoute: typeof DataDashboardRoute
  HeatTransferRoute: typeof HeatTransferRoute
  ManualRoute: typeof ManualRoute
  PipeFlowRoute: typeof PipeFlowRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  UnitsRoute: typeof UnitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-dashboard': {
      id: '/data-dashboard'
      path: '/data-dashboard'
      fullPath: '/data-dashboard'
      preLoaderRoute: typeof DataDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heat-transfer': {
      id: '/heat-transfer'
      path: '/heat-transfer'
      fullPath: '/heat-transfer'
      preLoaderRoute: typeof HeatTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipe-flow': {
      id: '/pipe-flow'
      path: '/pipe-flow'
      fullPath: '/pipe-flow'
      preLoaderRoute: typeof PipeFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataDashboardRoute: DataDashboardRoute,
  HeatTransferRoute: HeatTransferRoute,
  ManualRoute: ManualRoute,
  PipeFlowRoute: PipeFlowRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  UnitsRoute: UnitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
